name: instagram_clone
description: 基于Flutter的Instagram克隆应用
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  http: ^0.13.4
  cached_network_image: ^3.2.0
  image_picker: ^0.8.5+3
  shared_preferences: ^2.0.15
  flutter_staggered_grid_view: ^0.6.2
  font_awesome_flutter: ^10.1.0
  timeago: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 